### PR TITLE
WIP: fix count for gnu readline

### PR DESCRIPTION
**Pull request by JoshMcguigan**
This change adds escape sequences to mark color codes so that GNU readline counts them properly. I believe this would resolve NerdyPepper/pista#1, but I haven't tried it. 

This change breaks the tests which compare against the "reference implementation" (ansi_term), but all other unit tests pass. For that reason, this PR is a work in progress. I'm not sure if I'll get back around to finishing it, but I wanted to share the progress to this point.

Thanks for your work on this crate!

### CODE REVIEW

**Comment by mackwic** [comment]
Hmm, I guess we should change the reference implementation to something more canonic which is _also_ compatible with GNU Readline.
Breaking Readline is not acceptable, so I'm wanting to accept this change, but I'm not at ease to forgo all test against any reference implementation. What could be a better smoke test ?

**Comment by mackwic** [comment]
Thinking of it, pista is not maintained anymore. So this does not weight in favor of the change. Do you know any other use case broken by this issue ? (which is real, I'm trying to gauge the urgency of the fix)

**Comment by JoshMcguigan** [comment]
Thanks for digging into this. I still use pista, but to be honest, I can't even remember if I use the version compiled with this fix or not. Feel free to close this if you'd like.

**Comment by JoshMcguigan** [comment]
I can confirm that I had been using a version of pista which included this fix. 

Also, I've recently been working on a [shell prompt project of my own](https://github.com/JoshMcguigan/libps1) using `ansi_term`, and I can confirm `ansi_term` also has this issue. 

I'd probably switch from `ansi_term` to `colored` for my own library if this fix were merged, as I currently have some limitations in place to work around this issue. 

But I understand that this might be a niche use-case, and breaking away from the "reference implementation" isn't a decision to be taken lightly.

**Pull request closed without merging**
