### PR TITLE
Minor codestyle fixes

### PR DESCRIPTION
**Pull request by kylegalloway**
I made some updates based on clippy recommendations.

### CODE REVIEW

**Comment by brimatteng** [comment]
Beat me to putting this exact pr up by 11 hours

**Comment by kylegalloway** [comment]
Yeah @brimatteng I got the idea from http://matthias-endler.de/2017/hacktoberfest/ .... It's a good way to get into rust/rust open source.

**Comment by mackwic** [comment]
Good for me ! Thank you for the PR ! :)

It's only missing two things:
- Add yourself to the contributors in the Readme
- bump colored version to a new patch version

Per this repo policy, any significant accepted PR will elevate you to the role of contributor, which will give you push privileges on this repo (so that you can add this repo as a remote and create PR directly against mackwic/colored).

**Comment by kylegalloway** [comment]
These are done. Thanks for the feedback!

**Comment by mackwic** [comment]
Thank you for the PR !

Also you are now a contributor of `mackwic/colored` 🎉 :) Please use your new powers responsibly. Use PR for changes, and be kind to others.

**Pull request merged**
