### PR TITLE
Strikethrough

### PR DESCRIPTION
**Pull request by kylegalloway**
Adds strikethrough to solve Issue #7

### CODE REVIEW

**Comment by mackwic** [comment]
yeah ! 🎉 Thanks for the PR :)

LGTM (looks good to me) you can merge ! :)

**Comment by mackwic** [comment]
Ah no, it also needs a Changelog.md update. It could be in another PR as the 1.5.4 has other changes 🤔 

Also, it's now a minor version bump rather than a patch version bump, so let it be 1.6.0.

**Comment by kylegalloway** [comment]
I'm going to update the changelog here for all of my recent work. Then #35  and #36 can be pulled in.

**Comment by kylegalloway** [comment]
@mackwic please take a look and make sure I did the versioning correctly. If it looks good, feel free to merge #35 and then this.

**Comment by mackwic** [comment]
👌 excellent

**Pull request merged**
