### PR TITLE
Do not allocate when possible in impls of ColoredString

### PR DESCRIPTION
**Pull request by andy128k**

### CODE REVIEW

**Comment by kurtlawrence** [comment]
Hi @andy128k. Thanks for the PR.

Making `Colorize: Sized` means `Colorize` can not be used as a trait object, which some users may require, either now or in the future.

The spirit of the PR is sound, did you want to change each function to have a predicate of `Self: Sized`?

For example:

```rust
fn black(self) -> ColoredString
where
    Self: Sized,
{
    self.color(Color::Black)
}
```

Please also create a test to guarantee `Colorize` can be a trait object.

**Comment by andy128k** [comment]
@kurtlawrence `Colorize` cannot already be used as a trait object. It contains methods with generic parameters (e. g. [`color`](https://github.com/mackwic/colored/blob/master/src/lib.rs#L80)). 

Do you want me to replace `impl Into<Color>` with just `Color`? This will lead to other changes like this.

```
"blue".color("blue") -> "blue".color("blue".into())
```

**Comment by kurtlawrence** [comment]
Good point, I missed that.

Don't change the `Into<Color>` signatures, they may be in use.

Could you please still remove the `Sized` super trait, and change each function to be predicated on `Self: Sized`.

Looking over the `From` impls for `Color`, there is scope to reduce allocations as well, but that can be done in another PR.

**Comment by andy128k** [comment]
@kurtlawrence Done

**Pull request merged**
