### PR TITLE
pass by value for performance

### PR DESCRIPTION
**Pull request by manonthemat**

### CODE REVIEW

**Comment by mackwic** [comment]
I am not sure about this change... how is that more performant ?

**Comment by mackwic** [comment]
Without an answer, I will close this PR at the end of the week. You can answer with “I'll get back later”, that's OK.

**Comment by tforgione** [comment]
I guess OP made this PR after running `cargo clippy`:
```
warning: this argument is passed by reference, but would be more efficient if passed by value                    
  --> src/style.rs:88:19                                                                                         
   |                                                                                                             
88 |     pub fn to_str(&self) -> String {                                                                        
   |                   ^^^^^ help: consider passing by value instead: `self`                                     
   |                                                                                                             
   = note: #[warn(clippy::trivially_copy_pass_by_ref)] on by default                                             
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/master/index.html#trivially_copy_pass_by_ref
```

You can have [details on this](https://rust-lang.github.io/rust-clippy/master/#trivially_copy_pass_by_ref) but I think that a reference to the parameters takes more space than the object itself, and that's why taking it by value instead of by reference might be faster.

**Comment by mackwic** [comment]
@tforgione Thanks ! With the clippy rationale it makes more sense.

Too bad the OP is a low-quality contributor but then I guess this change is not harmful so let it be

**Pull request merged**
