### PR TITLE
Derive Copy and Clone for Color

### PR DESCRIPTION
**Pull request by KiChjang**

### CODE REVIEW

**Comment by mackwic** [comment]
Thanks for the PR ! 

Is there any other types that should be `Copy`able or `Clone`able ? Please add them if you think so.

LGTM, you can merge the PR 👍

**Comment by KiChjang** [comment]
Perhaps `ColoredString` should be clone as well?

I can't merge the PR since I have no write access to this repository.

**Comment by KiChjang** [comment]
I think I should make a version bump as well.

**Comment by mackwic** [comment]
Thank you for the contribution ! 🎉 

My policy is to add as a contributor everyone which successfully merge a PR. So I will now add you as a Colored contributor, wil give you commit rights, and you can now push PRs directly against this repo, review other PRs. 👍 

Don't push directly on master, though. ;)

**Comment by mackwic** [comment]
Version v.1.5.3 is now published, with updated Changelog.

**Pull request merged**
